[language-server.ruby-lsp]
command = "ruby-lsp"
args = []

[language-server.sorbet]
command = "srb"
args = ["tc", "--lsp"]

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]

[[language]]
name = "typescript"
language-servers = ["deno-lsp"]
auto-format = true

[[language]]
name = "ruby"
language-servers = [
  { name = "ruby-lsp", except-features = [
    "goto-definition",
    "goto-declaration",
    "goto-type-definition",
    "goto-reference",
    "goto-implementation",
    "completion",
    "rename-symbol",
  ] },
  "sorbet",
]

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true
