[language-server.ruby-lsp]
command = "ruby-lsp"
args = []

[language-server.ruby-lsp.config]
rubyVersionManager = 'asdf'
formatter = 'syntax_tree'

[language-server.sorbet]
command = "bundle"
args = ["exec", "srb", "tc", "--lsp"]

[language-server.rubocop]
command = "bundle"
args = ["exec", "rubocop", "--lsp"]

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]

[[language]]
name = "typescript"
language-id = "typescript"
scope = "source.ts"
injection-regex = "^(ts|typescript)$"
file-types = ["ts"]
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc", "package.json"]
auto-format = true
language-servers = ["deno-lsp"]

[[language]]
name = "ruby"
language-servers = [
  { name = "ruby-lsp", except-features = [
    "diagnostics",
    "goto-definition",
    "goto-declaration",
    "goto-type-definition",
    "goto-reference",
    "goto-implementation",
    "completion",
    "rename-symbol",
  ] },
  "rubocop",
  "sorbet",
]
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true
