[language-server.ruby-lsp]
command = "ruby-lsp"
args = []

[language-server.sorbet]
command = "srb"
args = ["tc", "--lsp"]

[language-server.stree]
command = "stree"
args = [
  "lsp",
  "--plugins",
  "plugin/single_quotes",
  "plugin/trailing_comma",
  '--print-width',
  '120',
]

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]

[[language]]
name = "typescript"
language-id = "typescript"
scope = "source.ts"
injection-regex = "^(ts|typescript)$"
file-types = ["ts"]
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc", "package.json"]
auto-format = true
language-servers = ["deno-lsp"]

[[language]]
name = "ruby"
language-servers = [
  { name = "ruby-lsp", except-features = [
    "goto-definition",
    "goto-declaration",
    "goto-type-definition",
    "goto-reference",
    "goto-implementation",
    "completion",
    "rename-symbol",
    "format",
  ] },
  "sorbet",
  "stree",
]
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true
